"""Initial migration

Revision ID: 3a32affbaa27
Revises: 6de312850b92
Create Date: 2024-10-11 10:32:04.467347

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a32affbaa27'
down_revision = '6de312850b92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('goals', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_clients'))
    )
    op.create_table('coaches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('specialization', sa.String(), nullable=True),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_coaches')),
    sa.UniqueConstraint('username', name=op.f('uq_coaches_username'))
    )
    op.create_table('coach_clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('coach_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name=op.f('fk_coach_clients_client_id_clients')),
    sa.ForeignKeyConstraint(['coach_id'], ['coaches.id'], name=op.f('fk_coach_clients_coach_id_coaches')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_coach_clients'))
    )
    op.create_table('sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('goal_progress', sa.Integer(), nullable=True),
    sa.Column('paid_status', sa.Boolean(), nullable=True),
    sa.Column('coach_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name=op.f('fk_sessions_client_id_clients')),
    sa.ForeignKeyConstraint(['coach_id'], ['coaches.id'], name=op.f('fk_sessions_coach_id_coaches')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sessions'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sessions')
    op.drop_table('coach_clients')
    op.drop_table('coaches')
    op.drop_table('clients')
    # ### end Alembic commands ###
