"""updated seed.py with agreements

Revision ID: c2e7e55d74a4
Revises: db4ea7a82d94
Create Date: 2024-10-29 10:06:27.341079

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2e7e55d74a4'
down_revision = 'db4ea7a82d94'
branch_labels = None
depends_on = None


def upgrade():
    # Create the Enum type
    agreement_status_enum = sa.Enum('SIGNED', 'SENT_BUT_NOT_SIGNED', 'NOT_SENT', name='agreementstatus')
    
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client_agreements', schema=None) as batch_op:
        # Add the new column with the Enum type
        batch_op.add_column(sa.Column('agreement_status', agreement_status_enum, nullable=False))
        # Drop the old column
        batch_op.drop_column('agreement_signed')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client_agreements', schema=None) as batch_op:
        # Re-add the old column
        batch_op.add_column(sa.Column('agreement_signed', sa.Boolean(), nullable=True))
        # Drop the new column
        batch_op.drop_column('agreement_status')

    # ### end Alembic commands ###