"""Remove ClientAgreement model

Revision ID: d297b523dd83
Revises: c2e7e55d74a4
Create Date: 2024-10-29 14:42:55.376976

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd297b523dd83'
down_revision = 'c2e7e55d74a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('client_agreements')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client_agreements',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('client_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('coach_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('agreement_status', postgresql.ENUM('SIGNED', 'SENT_BUT_NOT_SIGNED', 'NOT_SENT', name='agreementstatus'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name='fk_client_agreements_client_id_clients'),
    sa.ForeignKeyConstraint(['coach_id'], ['coaches.id'], name='fk_client_agreements_coach_id_coaches'),
    sa.PrimaryKeyConstraint('id', name='pk_client_agreements')
    )
    # ### end Alembic commands ###
