"""Create CleintAgreement model and update relationships

Revision ID: db4ea7a82d94
Revises: 
Create Date: 2024-10-29 08:43:50.395042

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db4ea7a82d94'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client_agreements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('coach_id', sa.Integer(), nullable=False),
    sa.Column('agreement_signed', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name=op.f('fk_client_agreements_client_id_clients')),
    sa.ForeignKeyConstraint(['coach_id'], ['coaches.id'], name=op.f('fk_client_agreements_coach_id_coaches')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_client_agreements'))
    )
    op.drop_table('coach_clients')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coach_clients',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('coach_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('client_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('notes', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name='fk_coach_clients_client_id_clients'),
    sa.ForeignKeyConstraint(['coach_id'], ['coaches.id'], name='fk_coach_clients_coach_id_coaches'),
    sa.PrimaryKeyConstraint('id', name='pk_coach_clients')
    )
    op.drop_table('client_agreements')
    # ### end Alembic commands ###
